
// Variables
@local = http://localhost:3000
@render = https://cse341-level-api.onrender.com



// - - - - - - - - - - - - - - - - - - - - - LOCAL HOST

### list all Levels
{{local}}/levels


### list Level by id
{{local}}/levels/63c76ab0287964cb34f7c9c6


### Create Level
POST {{local}}/levels HTTP/1.1
content-type: application/json

{"level_name":"test level","level_author":"kyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "green","bouncy": "on","causes_damage": "on"}]}


### Update Level
PUT {{local}}/levels/63c7979f2dfc9f2af1d4c3df HTTP/1.1 
content-type: application/json

{"level_name":"test level","level_author":"lyle","level_block_data":[{"grid_x": "11","grid_y": "6","width": "1","height": "1","color": "blue","bouncy": "on","causes_damage": "on"}]}


### Delete Level by Id
DELETE {{local}}/levels/63c76a5e287964cb34f7c9c5 HTTP/1.1



// - - - - - - - - - - - - - - - - - - - - - RENDER

### list all levels
{{render}}/levels


### list level by id
{{render}}/levels/63be5949e919669ee83e5d67


### Create level
POST {{render}}/levels HTTP/1.1
content-type: application/json

{"level_name":"render test level","level_author":"kyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "blue","bouncy": "on","causes_damage": "on"}]}


### Update level
PUT {{render}}/levels/63c7a0cbdf0072231995e958 HTTP/1.1 
content-type: application/json

{"level_name":"render test level 1.0","level_author":"lyle","level_block_data":[{"grid_x": "10","grid_y": "6","width": "1","height": "1","color": "red","bouncy": "on","causes_damage": "on"}]}


### Delete level by Id
DELETE {{render}}/levels/63be5924e919669ee83e5d66 HTTP/1.1
