
// Variables
@local = http://localhost:3000
@render = https://cse341-lesson2-119m.onrender.com



// - - - - - - - - - - - - - - - - - - - - - LOCAL HOST

### list all contacts
{{local}}/blocks


### list contact by id
{{local}}/blocks/63be53b5f0a60a8ef3aabfb2


### Create contact
POST {{local}}/blocks HTTP/1.1
content-type: application/json

{}


### Update contact
PUT {{local}}/blocks/63be51dc2bfc475c309c9970 HTTP/1.1 
content-type: application/json

{}


### Delete Contact by Id
DELETE {{local}}/blocks/63be51dc2bfc475c309c9970 HTTP/1.1



// - - - - - - - - - - - - - - - - - - - - - RENDER

### list all contacts
{{render}}/blocks


### list contact by id
{{render}}/blocks/63be5949e919669ee83e5d67


### Create contact
POST {{render}}/blocks HTTP/1.1
content-type: application/json

{}


### Update contact
PUT {{render}}/blocks/63be5924e919669ee83e5d66 HTTP/1.1 
content-type: application/json

{}


### Delete Contact by Id
DELETE {{render}}/blocks/63be5924e919669ee83e5d66 HTTP/1.1
